function segment(value: string): string {
  return encodeURIComponent(value)
}

export const API_ENDPOINTS = {
  health: '/health',
  models: '/v1/models',
  conversations: '/v1/conversations',
  conversation: (conversationId: string) =>
    `/v1/conversations/${segment(conversationId)}`,
  conversationMessages: (conversationId: string) =>
    `/v1/conversations/${segment(conversationId)}/messages`,
  chatStream: '/v1/chat/stream',
  messageFeedback: (messageId: string) =>
    `/v1/messages/${segment(messageId)}/feedback`,
  imageEdit: '/v1/images/edit',
  files: '/v1/files',
  file: (fileId: string) => `/v1/files/${segment(fileId)}`,
  projects: '/v1/projects',
  project: (projectId: string) => `/v1/projects/${segment(projectId)}`,
  developerRuntimes: '/v1/developer/runtimes',
  developerExecute: '/v1/developer/execute',
  securityScans: '/v1/security-scans',
  securityScan: (scanId: string) => `/v1/security-scans/${segment(scanId)}`,
  subscription: '/v1/subscription',
  billingCheckout: '/v1/billing/checkout',
  store: '/v1/store',
  storeActivate: '/v1/store/activate',
  researchPlan: '/v1/research/plan',
  credits: '/v1/credits',
  usageCosts: '/v1/usage-costs',
  profile: '/v1/profile',
  legalConsent: '/v1/legal/consent',
  voiceConfig: '/v1/voice/config',
  voiceSynthesize: '/v1/voice/synthesize',
  voiceTranscribe: '/v1/voice/transcribe',
  apiKeys: '/v1/api-keys',
  apiKey: (keyId: string) => `/v1/api-keys/${segment(keyId)}`,
  publicConfig: '/v1/public/config',
  publicJournal: '/v1/public/journal',
  maintenanceAccess: '/v1/maintenance/access',
  accessCodeValidate: '/v1/access-code/validate',
  accessCodeRedeem: '/v1/access-code/redeem',
  inviteValidate: '/v1/invites/validate',
  inviteRedeem: '/v1/invites/redeem',
  teamMode: '/v1/team-mode',
  teamJournal: '/v1/team/journal',
  teamWorkshop: '/v1/team/workshop',
  teamInvites: '/v1/team/invites',
  teamInvite: (inviteId: string) => `/v1/team/invites/${segment(inviteId)}`,
  adminDashboard: '/v1/admin/dashboard',
  adminSecurityEvents: '/v1/admin/security-events',
  adminConfig: '/v1/admin/config',
  adminConstructionMode: '/v1/admin/construction-mode',
  adminInvites: '/v1/admin/invites',
  adminInvite: (inviteId: string) => `/v1/admin/invites/${segment(inviteId)}`,
  adminJournal: '/v1/admin/journal',
  adminJournalAudit: '/v1/admin/journal/audit',
  adminPublishWorkshop: (releaseId: string) =>
    `/v1/admin/workshop/${segment(releaseId)}/publish`,
} as const
