import { LegalDocument, LegalSection } from '@/components/legal/legal-document'
import { LEGAL_CONTACT_EMAIL } from '@/lib/legal'
import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Acceptable Use Policy — Vurenn', description: 'Rules for safe and lawful use of Vurenn.' }

export default function AcceptableUsePage() {
  return (
    <LegalDocument title="Acceptable Use Policy" summary="These rules protect users, third parties, providers, and the Vurenn platform. They apply to the app, API, generated media, voice, files, projects, and connected devices.">
      <LegalSection title="1. Follow the law and respect rights"><p>You may not use Vurenn to violate law, regulation, court order, contractual obligation, intellectual-property right, privacy right, publicity right, or another person’s rights. Do not upload or request content you lack permission to use.</p></LegalSection>
      <LegalSection title="2. Harm, violence, and dangerous activity"><p>You may not use the Service to facilitate terrorism or violent extremism; plan or meaningfully assist violence; create weapons or harmful biological, chemical, or explosive materials; evade safety controls; promote suicide or self-harm; abuse or exploit a person or animal; or operate machinery or robots in a way that creates unreasonable risk. Benign safety, prevention, historical, or recovery-oriented discussion may be permitted.</p></LegalSection>
      <LegalSection title="3. Children and sexual content"><p>Any sexualization, grooming, exploitation, abuse, trafficking, or endangerment of a minor is strictly prohibited. Do not create, possess, request, transform, or distribute child sexual abuse material or sexual content involving a person who may be under 18. Apparent violations may be preserved and reported when required or appropriate.</p></LegalSection>
      <LegalSection title="4. Crime, fraud, and deception"><p>Do not facilitate fraud, scams, phishing, credential theft, identity theft, stalking, doxxing, extortion, evasion of law enforcement, trafficking, money laundering, market manipulation, academic impersonation, forged evidence, or deceptive impersonation. Clearly disclose synthetic media where omission would materially mislead people.</p></LegalSection>
      <LegalSection title="5. Cybersecurity"><p>Do not deploy malware, ransomware, destructive code, botnets, unauthorized surveillance, credential attacks, denial-of-service activity, or attempts to access systems without authorization. Defensive security research must be authorized, scoped, controlled, and designed to reduce harm.</p></LegalSection>
      <LegalSection title="6. Harassment and hateful abuse"><p>Do not threaten, terrorize, sexually exploit, relentlessly harass, or encourage violence or unlawful discrimination against people. Content that dehumanizes protected groups or is intended to recruit for hateful violence is prohibited.</p></LegalSection>
      <LegalSection title="7. Privacy and sensitive decisions"><p>Do not infer, expose, buy, sell, or exploit highly sensitive personal data without a lawful basis and permission. Do not use Vurenn as the sole decision-maker for employment, housing, credit, insurance, education admission, law enforcement, healthcare, legal rights, or other high-impact decisions. Qualified human review and all legally required notices, consent, and appeal processes are required.</p></LegalSection>
      <LegalSection title="8. Platform and API integrity"><p>Do not share secret keys, bypass limits, automate account creation, scrape the Service, interfere with security controls, probe other users’ data, resell access without written authorization, conceal the true user of an API request, or use Vurenn output or access to unlawfully compete, reverse engineer, or train another model in violation of applicable provider terms.</p></LegalSection>
      <LegalSection title="9. Enforcement"><p>Vurenn may block content, limit features, suspend or terminate accounts or keys, preserve relevant evidence, reverse credits obtained through abuse, and report conduct to providers or authorities when reasonably necessary or legally required. Enforcement may be automated or manual and may consider context, severity, repetition, and risk. Provider safety systems are not guaranteed to detect every violation.</p><p>To report abuse or appeal an enforcement decision, email <a className="text-primary underline" href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a> with sufficient detail. Do not send illegal media by email.</p></LegalSection>
      <LegalSection title="10. Changes"><p>We may update these rules to address new features, threats, provider requirements, or law. Continued use after notice of an updated policy constitutes acceptance where permitted; renewed affirmative consent will be requested when required.</p></LegalSection>
    </LegalDocument>
  )
}
