export type IntelligenceCategory =
  | 'Truth & reasoning'
  | 'Personal intelligence'
  | 'Projects & creation'
  | 'Voice & conversation'
  | 'Safety, privacy & control'

export type IntelligenceStatus = 'available' | 'beta' | 'foundation' | 'planned'

export interface IntelligenceFeature {
  id: string
  name: string
  category: IntelligenceCategory
  description: string
  status: IntelligenceStatus
  prompt?: string
}

export const INTELLIGENCE_CATEGORIES: IntelligenceCategory[] = [
  'Truth & reasoning',
  'Personal intelligence',
  'Projects & creation',
  'Voice & conversation',
  'Safety, privacy & control',
]

/**
 * The public source of truth for Vurenn's intelligence program.
 * `available` means usable today. `beta` means usable but still being refined.
 * `foundation` means supporting product work has shipped, but the full feature
 * is not promised yet. `planned` is a published direction, not a live feature.
 */
const CORE_INTELLIGENCE_FEATURES: IntelligenceFeature[] = [
  {
    id: 'confidence-autopsy',
    name: 'Confidence Autopsy',
    category: 'Truth & reasoning',
    description: 'Separates evidence, inference, uncertainty, and the assumptions carrying an answer.',
    status: 'available',
    prompt: 'Run a Confidence Autopsy on this. Separate evidence, inference, uncertainty, and load-bearing assumptions:',
  },
  {
    id: 'belief-update',
    name: 'Belief Update',
    category: 'Truth & reasoning',
    description: 'Shows what new evidence should change a conclusion and by approximately how much.',
    status: 'available',
    prompt: 'Create a Belief Update. Explain what evidence should change the conclusion, in which direction, and why:',
  },
  {
    id: 'claim-expiration-dates',
    name: 'Claim Expiration Dates',
    category: 'Truth & reasoning',
    description: 'Marks time-sensitive claims and tells you when each one should be checked again.',
    status: 'beta',
    prompt: 'Identify the time-sensitive claims here, give each a practical re-check date, and explain what could make it expire:',
  },
  {
    id: 'truth-debt',
    name: 'Truth Debt',
    category: 'Truth & reasoning',
    description: 'Keeps unresolved assumptions visible instead of quietly turning them into facts.',
    status: 'beta',
    prompt: 'Build a Truth Debt ledger for this decision. List unresolved assumptions, risk if wrong, and the cheapest way to verify each:',
  },
  {
    id: 'evidence-collision',
    name: 'Evidence Collision',
    category: 'Truth & reasoning',
    description: 'Finds where credible sources disagree and explains the real reason for the conflict.',
    status: 'available',
    prompt: 'Run an Evidence Collision analysis. Find the strongest credible disagreement and explain why the evidence conflicts:',
  },
  {
    id: 'answer-stress-test',
    name: 'Answer Stress Test',
    category: 'Truth & reasoning',
    description: 'Attempts to break an answer with counterexamples, edge cases, and hostile assumptions.',
    status: 'available',
    prompt: 'Stress-test this answer. Try to break it with counterexamples, edge cases, and hostile assumptions, then repair what fails:',
  },
  {
    id: 'false-certainty-alarm',
    name: 'False Certainty Alarm',
    category: 'Truth & reasoning',
    description: 'Flags confident wording that is not supported by equally strong evidence.',
    status: 'available',
    prompt: 'Act as a False Certainty Alarm. Flag every claim whose confidence exceeds its evidence and rewrite it honestly:',
  },
  {
    id: 'missing-voice-detector',
    name: 'Missing Voice Detector',
    category: 'Truth & reasoning',
    description: 'Surfaces stakeholders and perspectives that are absent from a plan or argument.',
    status: 'available',
    prompt: 'Use Missing Voice Detector on this. Identify absent stakeholders, perspectives, and incentives that could change the conclusion:',
  },
  {
    id: 'prediction-receipts',
    name: 'Prediction Receipts',
    category: 'Truth & reasoning',
    description: 'Turns forecasts into dated, testable claims that can later be scored against reality.',
    status: 'foundation',
  },
  {
    id: 'reality-check',
    name: 'Reality Check',
    category: 'Truth & reasoning',
    description: 'Gives the shortest honest assessment of what is likely, unlikely, or still unknown.',
    status: 'available',
    prompt: 'Give me a direct Reality Check. Separate what is likely, unlikely, and genuinely unknown. Do not soften the conclusion:',
  },
  {
    id: 'memory-negotiation',
    name: 'Memory Negotiation',
    category: 'Personal intelligence',
    description: 'Lets a person approve, revise, or reject what Vurenn proposes to remember.',
    status: 'foundation',
  },
  {
    id: 'future-self-review',
    name: 'Future-Self Review',
    category: 'Personal intelligence',
    description: 'Reviews a decision from the perspective of you in six months, one year, and five years.',
    status: 'available',
    prompt: 'Run a Future-Self Review of this decision from six months, one year, and five years ahead. Include likely gratitude and regret:',
  },
  {
    id: 'personal-contradiction-map',
    name: 'Personal Contradiction Map',
    category: 'Personal intelligence',
    description: 'Surfaces tensions between stated goals, values, habits, and recent decisions.',
    status: 'planned',
  },
  {
    id: 'energy-aware-responses',
    name: 'Energy-Aware Responses',
    category: 'Personal intelligence',
    description: 'Adjusts density and next steps for low-energy, normal, or focused moments.',
    status: 'available',
    prompt: 'I am low on energy. Give me the smallest useful answer and one realistic next action for:',
  },
  {
    id: 'decision-personality',
    name: 'Decision Personality',
    category: 'Personal intelligence',
    description: 'Adapts decision support to how a person weighs speed, risk, evidence, and reversibility.',
    status: 'planned',
  },
  {
    id: 'regret-minimizer',
    name: 'Regret Minimizer',
    category: 'Personal intelligence',
    description: 'Compares likely regret, reversibility, and cost of delay across choices.',
    status: 'available',
    prompt: 'Run Regret Minimizer on these options. Compare likely regret, reversibility, cost of delay, and the safest next experiment:',
  },
  {
    id: 'values-lock',
    name: 'Values Lock',
    category: 'Personal intelligence',
    description: 'Checks recommendations against values the user explicitly chooses for the decision.',
    status: 'beta',
    prompt: 'Before advising me, ask for the three values this decision must protect. Then evaluate every option against them:',
  },
  {
    id: 'life-context-boundaries',
    name: 'Life Context Boundaries',
    category: 'Personal intelligence',
    description: 'Keeps advice from crossing contexts the user has marked private or irrelevant.',
    status: 'planned',
  },
  {
    id: 'memory-temperature',
    name: 'Memory Temperature',
    category: 'Personal intelligence',
    description: 'Distinguishes temporary context from durable facts instead of treating every detail equally.',
    status: 'foundation',
  },
  {
    id: 'relationship-context',
    name: 'Relationship Context',
    category: 'Personal intelligence',
    description: 'Tracks roles and communication preferences without pretending to know people it has not met.',
    status: 'planned',
  },
  {
    id: 'project-gravity',
    name: 'Project Gravity',
    category: 'Projects & creation',
    description: 'Keeps project chats anchored to the objective, files, and working instructions.',
    status: 'beta',
  },
  {
    id: 'dead-end-detector',
    name: 'Dead-End Detector',
    category: 'Projects & creation',
    description: 'Warns when activity is increasing but progress toward the outcome is not.',
    status: 'planned',
  },
  {
    id: 'invisible-work-tracker',
    name: 'Invisible Work Tracker',
    category: 'Projects & creation',
    description: 'Captures decisions, research, rejected options, and other work a task list misses.',
    status: 'planned',
  },
  {
    id: 'project-pulse',
    name: 'Project Pulse',
    category: 'Projects & creation',
    description: 'Summarizes momentum, blockers, uncertainty, and the next meaningful action.',
    status: 'foundation',
  },
  {
    id: 'scope-drift-replay',
    name: 'Scope Drift Replay',
    category: 'Projects & creation',
    description: 'Shows when the project changed direction and which decisions caused the shift.',
    status: 'planned',
  },
  {
    id: 'assumption-sandbox',
    name: 'Assumption Sandbox',
    category: 'Projects & creation',
    description: 'Recalculates a plan after changing one or more important assumptions.',
    status: 'available',
    prompt: 'Create an Assumption Sandbox for this plan. Identify the five load-bearing assumptions and show what changes if each one is false:',
  },
  {
    id: 'knowledge-decay-alerts',
    name: 'Knowledge Decay Alerts',
    category: 'Projects & creation',
    description: 'Identifies project knowledge that is likely stale and should be refreshed.',
    status: 'planned',
  },
  {
    id: 'decision-dependency-graph',
    name: 'Decision Dependency Graph',
    category: 'Projects & creation',
    description: 'Maps which decisions depend on other facts, approvals, and unresolved choices.',
    status: 'available',
    prompt: 'Build a Decision Dependency Graph in a clear indented outline. Show dependencies, blockers, reversible choices, and the critical path:',
  },
  {
    id: 'project-constitution',
    name: 'Project Constitution',
    category: 'Projects & creation',
    description: 'Defines purpose, non-negotiables, decision rules, scope, and the definition of done.',
    status: 'available',
    prompt: 'Draft a Project Constitution. Include purpose, users, non-negotiables, exclusions, decision rules, risks, and a measurable definition of done for:',
  },
  {
    id: 'completion-proof',
    name: 'Completion Proof',
    category: 'Projects & creation',
    description: 'Requires observable evidence before a task or project can be called complete.',
    status: 'available',
    prompt: 'Create Completion Proof for this work. Define the evidence, tests, acceptance criteria, and failure conditions required before calling it done:',
  },
  {
    id: 'conversational-memory-marker',
    name: 'Conversational Memory Marker',
    category: 'Voice & conversation',
    description: 'Makes it explicit when a spoken detail is temporary, important, or worth remembering.',
    status: 'planned',
  },
  {
    id: 'thinking-silence',
    name: 'Thinking Silence',
    category: 'Voice & conversation',
    description: 'Uses natural pauses instead of filler while Vurenn prepares a voice response.',
    status: 'beta',
  },
  {
    id: 'emotional-pace-matching',
    name: 'Emotional Pace Matching',
    category: 'Voice & conversation',
    description: 'Adjusts speaking pace without imitating identity, accent, or emotional distress.',
    status: 'planned',
  },
  {
    id: 'private-whisper-mode',
    name: 'Private Whisper Mode',
    category: 'Voice & conversation',
    description: 'Produces short, discreet spoken answers for public or shared spaces.',
    status: 'planned',
  },
  {
    id: 'voice-fork',
    name: 'Voice Fork',
    category: 'Voice & conversation',
    description: 'Branches a spoken idea into alternatives without losing the original thread.',
    status: 'planned',
  },
  {
    id: 'argument-referee',
    name: 'Argument Referee',
    category: 'Voice & conversation',
    description: 'Summarizes agreement, disagreement, evidence, and unresolved questions between people.',
    status: 'available',
    prompt: 'Act as an Argument Referee. Separate agreement, disagreement, evidence, assumptions, and the fairest next question in this exchange:',
  },
  {
    id: 'conversation-repair',
    name: 'Conversation Repair',
    category: 'Voice & conversation',
    description: 'Detects a misunderstanding and proposes a concise reset that preserves dignity.',
    status: 'available',
    prompt: 'Help repair this conversation. Identify the likely misunderstanding, steelman both sides, and draft a short reset that preserves dignity:',
  },
  {
    id: 'interruption-bookmark',
    name: 'Interruption Bookmark',
    category: 'Voice & conversation',
    description: 'Returns to an unfinished thought after an interruption without losing context.',
    status: 'planned',
  },
  {
    id: 'say-less-signal',
    name: 'Say Less Signal',
    category: 'Voice & conversation',
    description: 'Compresses a response to the smallest answer that still changes what the user should do.',
    status: 'available',
    prompt: 'Use Say Less Signal. Give me only the conclusion, the reason that changes it, and one next action:',
  },
  {
    id: 'verbal-whiteboard',
    name: 'Verbal Whiteboard',
    category: 'Voice & conversation',
    description: 'Turns a spoken brainstorm into an organized outline and action map.',
    status: 'available',
    prompt: 'Turn this brainstorm into a Verbal Whiteboard: themes, decisions, open questions, owners, and next actions:',
  },
  {
    id: 'private-computation-receipt',
    name: 'Private Computation Receipt',
    category: 'Safety, privacy & control',
    description: 'Explains what data a task used, where it was processed, and what was retained.',
    status: 'foundation',
  },
  {
    id: 'sensitive-detail-shield',
    name: 'Sensitive Detail Shield',
    category: 'Safety, privacy & control',
    description: 'Detects likely secrets and personal identifiers before they leave the composer.',
    status: 'planned',
  },
  {
    id: 'provider-choice-by-privacy',
    name: 'Provider Choice by Privacy',
    category: 'Safety, privacy & control',
    description: 'Routes work according to a user-selected privacy requirement when compatible providers exist.',
    status: 'planned',
  },
  {
    id: 'one-time-memory',
    name: 'One-Time Memory',
    category: 'Safety, privacy & control',
    description: 'Allows context for one task without making it durable account memory.',
    status: 'foundation',
  },
  {
    id: 'digital-witness',
    name: 'Digital Witness',
    category: 'Safety, privacy & control',
    description: 'Creates a tamper-evident record of a decision, its sources, and its timestamp.',
    status: 'planned',
  },
  {
    id: 'consent-boundaries',
    name: 'Consent Boundaries',
    category: 'Safety, privacy & control',
    description: 'Requires explicit permission before using shared personal material in a new context.',
    status: 'foundation',
  },
  {
    id: 'harmful-drift-detection',
    name: 'Harmful Drift Detection',
    category: 'Safety, privacy & control',
    description: 'Looks for a conversation gradually moving toward self-harm, violence, or dangerous misuse.',
    status: 'beta',
  },
  {
    id: 'human-authority-map',
    name: 'Human Authority Map',
    category: 'Safety, privacy & control',
    description: 'Shows which actions require a human decision, professional review, or account owner approval.',
    status: 'planned',
  },
  {
    id: 'data-escape-hatch',
    name: 'Data Escape Hatch',
    category: 'Safety, privacy & control',
    description: 'Exports user-owned work in common formats and provides a clear deletion path.',
    status: 'foundation',
  },
  {
    id: 'truth-mode-emergency-stop',
    name: 'Truth Mode Emergency Stop',
    category: 'Safety, privacy & control',
    description: 'Stops generation immediately and preserves the user message so a safer direction can be chosen.',
    status: 'available',
    prompt: 'Stop and reset. State what went wrong in the prior approach, what is safe to continue, and ask the one question needed to proceed honestly:',
  },
]

const EXPANSION_INTELLIGENCE_FEATURES: IntelligenceFeature[] = [
  {
    id: 'truth-ledger',
    name: 'Truth Ledger',
    category: 'Truth & reasoning',
    description: 'Separates verified facts, assumptions, estimates, and opinions so they cannot quietly blur together.',
    status: 'available',
    prompt: 'Build a Truth Ledger for this. Separate verified facts, assumptions, estimates, opinions, and claims that still require evidence:',
  },
  {
    id: 'contradiction-radar',
    name: 'Contradiction Radar',
    category: 'Truth & reasoning',
    description: 'Finds conflicts across sources, files, and earlier statements before they affect a decision.',
    status: 'available',
    prompt: 'Run Contradiction Radar. Identify every meaningful conflict, explain whether it is real or only apparent, and say what would resolve it:',
  },
  {
    id: 'confidence-map',
    name: 'Confidence Map',
    category: 'Truth & reasoning',
    description: 'Maps which parts of an answer are strongly supported, plausible, weak, or unknown.',
    status: 'available',
    prompt: 'Create a Confidence Map for this answer. Label each important claim as strongly supported, plausible, weak, or unknown and explain why:',
  },
  {
    id: 'evidence-timeline',
    name: 'Evidence Timeline',
    category: 'Truth & reasoning',
    description: 'Organizes claims and supporting evidence chronologically to expose outdated conclusions.',
    status: 'available',
    prompt: 'Build an Evidence Timeline. Put the important claims, events, and supporting evidence in date order and flag anything outdated:',
  },
  {
    id: 'source-freshness-monitor',
    name: 'Source Freshness Monitor',
    category: 'Truth & reasoning',
    description: 'Explains which sources are still current and which claims should be checked again.',
    status: 'available',
    prompt: 'Run Source Freshness Monitor. Check the age and current relevance of each source or claim, then identify what needs a fresh search:',
  },
  {
    id: 'assumption-inspector',
    name: 'Assumption Inspector',
    category: 'Truth & reasoning',
    description: 'Makes hidden assumptions reviewable and correctable before work continues.',
    status: 'available',
    prompt: 'Run Assumption Inspector. List the hidden assumptions, impact if each is wrong, and the quickest way to test them:',
  },
  {
    id: 'steelman-mode',
    name: 'Steelman Mode',
    category: 'Truth & reasoning',
    description: 'Builds the strongest fair version of opposing views before drawing a conclusion.',
    status: 'available',
    prompt: 'Use Steelman Mode. Present the strongest fair version of each major opposing view, then explain what survives comparison:',
  },
  {
    id: 'missing-evidence-detector',
    name: 'Missing-Evidence Detector',
    category: 'Truth & reasoning',
    description: 'Identifies the absent evidence most likely to change the answer.',
    status: 'available',
    prompt: 'Run Missing-Evidence Detector. Identify the missing evidence most likely to change the conclusion and how to obtain it:',
  },
  {
    id: 'claim-level-citations',
    name: 'Claim-Level Citations',
    category: 'Truth & reasoning',
    description: 'Connects citations to the exact claims they support instead of collecting links at the bottom.',
    status: 'available',
    prompt: 'Research this and use Claim-Level Citations. Attach a credible current source to each important factual claim and separate inference from fact:',
  },
  {
    id: 'decision-reversal-test',
    name: 'Decision Reversal Test',
    category: 'Truth & reasoning',
    description: 'Shows the conditions under which the opposite decision would become better.',
    status: 'available',
    prompt: 'Run a Decision Reversal Test. State the current best choice, then identify the exact conditions that would make the opposite choice better:',
  },
  {
    id: 'project-pulse-command-center',
    name: 'Project Pulse Command Center',
    category: 'Projects & creation',
    description: 'Turns project momentum, blockers, uncertainty, and next actions into one living command view.',
    status: 'beta',
    prompt: 'Run Project Pulse. Summarize momentum, blockers, uncertainty, recent decisions, and the single best next action for:',
  },
  {
    id: 'living-project-memory',
    name: 'Living Project Memory',
    category: 'Projects & creation',
    description: 'Maintains an editable project brief that evolves with chats, files, and decisions.',
    status: 'foundation',
  },
  {
    id: 'context-curator',
    name: 'Context Curator',
    category: 'Projects & creation',
    description: 'Keeps useful project context close while preventing irrelevant material from crowding the work.',
    status: 'foundation',
  },
  {
    id: 'knowledge-expiration-dates',
    name: 'Knowledge Expiration Dates',
    category: 'Projects & creation',
    description: 'Assigns review dates to project knowledge that can become stale.',
    status: 'available',
    prompt: 'Assign Knowledge Expiration Dates to the important information in this project. Explain what could make each item stale and when to re-check it:',
  },
  {
    id: 'file-relationship-map',
    name: 'File Relationship Map',
    category: 'Projects & creation',
    description: 'Connects related documents, chats, people, claims, and decisions into a navigable map.',
    status: 'beta',
    prompt: 'Create a File Relationship Map from the attached and saved project knowledge. Explain how the files, claims, decisions, and gaps connect:',
  },
  {
    id: 'decision-journal',
    name: 'Decision Journal',
    category: 'Projects & creation',
    description: 'Records what was decided, why, using which evidence, and what would trigger a review.',
    status: 'available',
    prompt: 'Create a Decision Journal entry: decision, date, owner, evidence, alternatives rejected, risks, and the trigger for reconsidering it:',
  },
  {
    id: 'project-time-machine',
    name: 'Project Time Machine',
    category: 'Projects & creation',
    description: 'Reconstructs the known state, assumptions, and priorities from an earlier point in a project.',
    status: 'planned',
  },
  {
    id: 'automatic-handoff-pack',
    name: 'Automatic Handoff Pack',
    category: 'Projects & creation',
    description: 'Creates a complete, understandable briefing when another person joins the work.',
    status: 'available',
    prompt: 'Create an Automatic Handoff Pack: purpose, current state, decisions, rejected options, important files, risks, owners, and next actions for:',
  },
  {
    id: 'change-impact-preview',
    name: 'Change-Impact Preview',
    category: 'Projects & creation',
    description: 'Predicts which plans, files, decisions, and users a proposed change could affect.',
    status: 'available',
    prompt: 'Run a Change-Impact Preview. Map the direct effects, downstream effects, affected people and files, risks, and rollback path for:',
  },
  {
    id: 'project-health-score',
    name: 'Project Health Score',
    category: 'Projects & creation',
    description: 'Scores clarity, momentum, risk, evidence quality, ownership, and unresolved decisions.',
    status: 'available',
    prompt: 'Calculate a Project Health Score from 0–100. Score clarity, momentum, risk, evidence, ownership, and unresolved decisions, then justify every score:',
  },
  {
    id: 'personal-glossary',
    name: 'Personal Glossary',
    category: 'Personal intelligence',
    description: 'Learns user-approved terminology, abbreviations, product names, and definitions.',
    status: 'foundation',
  },
  {
    id: 'explanation-fingerprint',
    name: 'Explanation Fingerprint',
    category: 'Personal intelligence',
    description: 'Adapts explanations to examples, visuals, analogies, direct instruction, or another approved style.',
    status: 'foundation',
  },
  {
    id: 'tone-recipes',
    name: 'Tone Recipes',
    category: 'Personal intelligence',
    description: 'Saves reusable response styles without changing Vurenn’s honesty or safety standards.',
    status: 'beta',
  },
  {
    id: 'cognitive-load-control',
    name: 'Cognitive Load Control',
    category: 'Personal intelligence',
    description: 'Compresses complexity and next actions when a user explicitly wants less mental load.',
    status: 'available',
    prompt: 'Use Cognitive Load Control. Reduce this to the smallest clear explanation, the one decision that matters, and one realistic next action:',
  },
  {
    id: 'memory-boundaries',
    name: 'Memory Boundaries',
    category: 'Personal intelligence',
    description: 'Separates work, school, family, and private context instead of merging everything together.',
    status: 'planned',
  },
  {
    id: 'correct-me-mode',
    name: 'Correct-Me Mode',
    category: 'Personal intelligence',
    description: 'Prioritizes respectful correction over agreement when the evidence points elsewhere.',
    status: 'available',
    prompt: 'Use Correct-Me Mode. Do not agree with me automatically. Identify what I may have wrong, explain the evidence, and give the most honest correction:',
  },
  {
    id: 'learning-mirror',
    name: 'Learning Mirror',
    category: 'Personal intelligence',
    description: 'Reflects demonstrated understanding and recommends what to reinforce next.',
    status: 'available',
    prompt: 'Act as a Learning Mirror. Based only on what I demonstrate here, identify what I understand, what is shaky, and the best next practice:',
  },
  {
    id: 'personal-briefing',
    name: 'Personal Briefing',
    category: 'Personal intelligence',
    description: 'Creates an optional concise briefing from active projects and unfinished work.',
    status: 'planned',
  },
  {
    id: 'conversation-temperature',
    name: 'Conversation Temperature',
    category: 'Personal intelligence',
    description: 'Adjusts calmness, directness, and density without pretending to diagnose emotion.',
    status: 'foundation',
  },
  {
    id: 'forgetfulness-center',
    name: 'Forgetfulness Center',
    category: 'Personal intelligence',
    description: 'Surfaces old or unused memories for review instead of retaining them invisibly forever.',
    status: 'planned',
  },
  {
    id: 'natural-language-workflows',
    name: 'Natural-Language Workflows',
    category: 'Projects & creation',
    description: 'Turns a repeated process described in ordinary language into a reviewable workflow.',
    status: 'available',
    prompt: 'Turn this repeated process into a Natural-Language Workflow with triggers, inputs, steps, approval points, failure handling, and an undo plan:',
  },
  {
    id: 'approval-queue',
    name: 'Approval Queue',
    category: 'Safety, privacy & control',
    description: 'Collects proposed external actions in one review surface before anything is executed.',
    status: 'planned',
  },
  {
    id: 'action-receipts',
    name: 'Action Receipts',
    category: 'Safety, privacy & control',
    description: 'Records what changed, why it changed, what evidence was used, and how to undo it.',
    status: 'foundation',
  },
  {
    id: 'failure-safe-automations',
    name: 'Failure-Safe Automations',
    category: 'Safety, privacy & control',
    description: 'Stops a workflow when results fall outside user-approved expectations.',
    status: 'planned',
  },
  {
    id: 'cost-preview',
    name: 'Cost Preview',
    category: 'Safety, privacy & control',
    description: 'Estimates credits and likely provider usage before expensive work begins.',
    status: 'foundation',
  },
  {
    id: 'smart-upload-inbox',
    name: 'Smart Upload Inbox',
    category: 'Projects & creation',
    description: 'Categorizes uploaded material and recommends the right project and tool without moving it silently.',
    status: 'planned',
  },
  {
    id: 'watchlists',
    name: 'Watchlists',
    category: 'Projects & creation',
    description: 'Monitors approved sites, topics, prices, documents, or competitors for meaningful changes.',
    status: 'planned',
  },
  {
    id: 'workflow-replay',
    name: 'Workflow Replay',
    category: 'Projects & creation',
    description: 'Reruns a successful reviewed process with new inputs while preserving its controls.',
    status: 'planned',
  },
  {
    id: 'reusable-capability-cards',
    name: 'Reusable Capability Cards',
    category: 'Projects & creation',
    description: 'Saves useful procedures as portable, understandable cards for future projects.',
    status: 'foundation',
  },
  {
    id: 'quiet-background-work',
    name: 'Quiet Background Work',
    category: 'Projects & creation',
    description: 'Keeps approved long work out of the conversation while preserving visible status and stop controls.',
    status: 'planned',
  },
  {
    id: 'artifact-studio',
    name: 'Artifact Studio',
    category: 'Projects & creation',
    description: 'Edits reports, images, spreadsheets, plans, and presentations beside the conversation.',
    status: 'planned',
  },
  {
    id: 'audience-simulator',
    name: 'Audience Simulator',
    category: 'Projects & creation',
    description: 'Previews how different intended audiences may understand or misunderstand a message.',
    status: 'available',
    prompt: 'Run Audience Simulator. Show how the intended audiences may interpret, trust, misunderstand, or resist this, then improve it without manipulating them:',
  },
  {
    id: 'one-idea-many-formats',
    name: 'One Idea, Many Formats',
    category: 'Projects & creation',
    description: 'Transforms one approved idea into a coordinated set of useful formats.',
    status: 'available',
    prompt: 'Use One Idea, Many Formats. Turn this into a concise email, social post, presentation outline, spoken script, and executive summary while keeping the facts consistent:',
  },
  {
    id: 'visual-explanation-builder',
    name: 'Visual Explanation Builder',
    category: 'Projects & creation',
    description: 'Chooses and drafts a diagram when relationships are clearer visually than in prose.',
    status: 'available',
    prompt: 'Use Visual Explanation Builder. Choose the smallest useful diagram type and produce a clear Mermaid diagram plus a short explanation for:',
  },
  {
    id: 'interactive-answer-blocks',
    name: 'Interactive Answer Blocks',
    category: 'Projects & creation',
    description: 'Turns responses into editable calculators, checklists, comparisons, and timelines.',
    status: 'planned',
  },
  {
    id: 'privacy-lens',
    name: 'Privacy Lens',
    category: 'Safety, privacy & control',
    description: 'Highlights sensitive details and unnecessary exposure before content is shared.',
    status: 'available',
    prompt: 'Run Privacy Lens. Identify sensitive or unnecessary personal information, explain the exposure risk, and provide a safely redacted version:',
  },
  {
    id: 'data-lineage',
    name: 'Data Lineage',
    category: 'Safety, privacy & control',
    description: 'Shows where important information originated and which outputs used it.',
    status: 'foundation',
  },
  {
    id: 'redacted-processing-mode',
    name: 'Redacted Processing Mode',
    category: 'Safety, privacy & control',
    description: 'Removes direct identifiers before compatible outside processing occurs.',
    status: 'planned',
  },
  {
    id: 'secure-share-capsules',
    name: 'Secure Share Capsules',
    category: 'Safety, privacy & control',
    description: 'Creates expiring protected shares with clear access and download controls.',
    status: 'planned',
  },
  {
    id: 'vurenn-compass',
    name: 'Vurenn Compass',
    category: 'Personal intelligence',
    description: 'Reviews decisions, progress, risks, abandoned goals, and the next priorities worth attention.',
    status: 'available',
    prompt: 'Run Vurenn Compass. Review decisions, progress, risks, abandoned goals, unresolved commitments, and recommend the three priorities that deserve attention next:',
  },
]

export const INTELLIGENCE_FEATURES: IntelligenceFeature[] = [
  ...CORE_INTELLIGENCE_FEATURES,
  ...EXPANSION_INTELLIGENCE_FEATURES,
]

export const FEATURE_STATUS_LABELS: Record<IntelligenceStatus, string> = {
  available: 'Available',
  beta: 'Beta',
  foundation: 'Foundation shipped',
  planned: 'Planned',
}
